In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("Inputdata - Sheet1.csv")
df.head()

,Campaign name,Day,Delivery status,Delivery level,Amount spent (INR),Impressions,"CPM (cost per 1,000 impressions)",Reach,Frequency,CTR (link click-through rate),...,CTR (all),Link clicks,Landing page views,Result Type,Results,Purchase ROAS (return on ad spend),Attribution setting,Cost per result,Reporting starts,Reporting ends
0,ForeignSales-AsiaAntartrica,3/31/2024,active,campaign,1033.89,21966,47.06774,20810,1.055550,0.883183,...,1.884731,194.0,91.0,freewebinarThankyoupage,9.0,NaN,7-day click or 1-day view,114.8767,3/31/2024,3/31/2024
1,Feedbackrs9,3/31/2024,inactive,campaign,497.70,5774,86.19674,5590,1.032916,0.381018,...,0.865951,22.0,14.0,NaN,1.0,NaN,7-day click or 1-day view,NaN,3/31/2024,3/31/2024
2,ForeignSales-AsiaAntartrica,3/29/2024,active,campaign,0.00,0,NaN,0,0.000000,NaN,...,NaN,NaN,NaN,freewebinarThankyoupage,1.0,NaN,7-day click or 1-day view,0.0000,3/29/2024,3/29/2024
3,Feedbackrs9,3/28/2024,inactive,campaign,0.00,0,NaN,0,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,7-day click or 1-day view,NaN,3/28/2024,3/28/2024
4,ForeignSales-AsiaAntartrica,3/27/2024,active,campaign,0.00,0,NaN,0,0.000000,NaN,...,NaN,NaN,NaN,freewebinarThankyoupage,1.0,NaN,7-day click or 1-day view,0.0000,3/27/2024,3/27/2024

In [3]:
#Converting 'Day' column to datetime format
df['Day'] = pd.to_datetime(df['Day'])

# Sorting DataFrame by 'Day'
df = df.sort_values(by='Day')

# Function to convert date to desired format
def convert_to_custom_date_format(date):
    day_of_week = date.strftime('%A')[:3]
    month = date.strftime('%B')[:3]
    return f"{date.day}{month} ({day_of_week})"

# Applying the function to 'Day' column
df['Day'] = df['Day'].apply(convert_to_custom_date_format)



# Displaying the DataFrame
print(df)

                                        Campaign name          Day  \
45                                Foreign|Sales|Tamil   1Mar (Fri)
44  3dayslive – Copy 2 - Advantage+ shopping campaign   1Mar (Fri)
43                                   3dayslive – Copy   1Mar (Fri)
42  3dayslive – Copy 2 - Advantage+ shopping campaign   2Mar (Sat)
41                                Foreign|Sales|Tamil   2Mar (Sat)
40                                Foreign|Sales|Tamil   3Mar (Sun)
39                                   3dayslive – Copy   3Mar (Sun)
38  3dayslive – Copy 2 - Advantage+ shopping campaign   3Mar (Sun)
37  Foreign|Sales|Tamil - Advantage+ shopping camp...   3Mar (Sun)
36                                Foreign|Sales|Tamil   4Mar (Mon)
35                                   3dayslive – Copy   4Mar (Mon)
34  3dayslive – Copy 2 - Advantage+ shopping campaign   4Mar (Mon)
32                                   3dayslive – Copy   5Mar (Tue)
33  3dayslive – Copy 2 - Advantage+ shopping campaign   5Mar (Tue)
31                                Foreign|Sales|Tamil   6Mar (Wed)
30  3dayslive – Copy 2 - Advantage+ shopping campaign   6Mar (Wed)
29  3dayslive – Copy 2 - Advantage+ shopping campaign   7Mar (Thu)
28  3dayslive – Copy 2 - Advantage+ shopping campaign   8Mar (Fri)
27  Foreign|Sales|Tamil - Advantage+ shopping camp...  16Mar (Sat)
26  Foreign|Sales|Tamil - Advantage+ shopping camp...  17Mar (Sun)
25                                        Feedbackrs9  17Mar (Sun)
24  Foreign|Sales|Tamil - Advantage+ shopping camp...  18Mar (Mon)
23                                        Feedbackrs9  18Mar (Mon)
22  Foreign|Sales|Tamil - Advantage+ shopping camp...  19Mar (Tue)
20                                        Feedbackrs9  19Mar (Tue)
21                        ForeignSales-AsiaAntartrica  19Mar (Tue)
19                                        Feedbackrs9  20Mar (Wed)
18                        ForeignSales-AsiaAntartrica  20Mar (Wed)
17  Foreign|Sales|Tamil - Advantage+ shopping camp...  21Mar (Thu)
16                                        Feedbackrs9  21Mar (Thu)
15                        ForeignSales-AsiaAntartrica  21Mar (Thu)
14  Foreign|Sales|Tamil - Advantage+ shopping camp...  22Mar (Fri)
13                                        Feedbackrs9  22Mar (Fri)
12                        ForeignSales-AsiaAntartrica  22Mar (Fri)
10                                        Feedbackrs9  23Mar (Sat)
11                        ForeignSales-AsiaAntartrica  23Mar (Sat)
9                                         Feedbackrs9  24Mar (Sun)
8                         ForeignSales-AsiaAntartrica  24Mar (Sun)
7                         ForeignSales-AsiaAntartrica  25Mar (Mon)
6                                         Feedbackrs9  26Mar (Tue)
5                         ForeignSales-AsiaAntartrica  26Mar (Tue)
4                         ForeignSales-AsiaAntartrica  27Mar (Wed)
3                                         Feedbackrs9  28Mar (Thu)
2                         ForeignSales-AsiaAntartrica  29Mar (Fri)
1                                         Feedbackrs9  31Mar (Sun)
0                         ForeignSales-AsiaAntartrica  31Mar (Sun)

   Delivery status Delivery level  Amount spent (INR)  Impressions  \
45        inactive       campaign              484.26         3287
44        inactive       campaign             1899.99        17113
43        inactive       campaign                0.00            0
42        inactive       campaign             1896.02        17766
41        inactive       campaign              384.46         2808
40        inactive       campaign                0.00            0
39        inactive       campaign                0.00            0
38        inactive       campaign             1520.26        12909
37        inactive       campaign              391.27          985
36        inactive       campaign                0.00            0
35        inactive       campaign                0.00            0
34        inactive       campaign                0.00            0
32        inactive       campaign                0.00            0
33        inactive       campaign                0.00            0
31        inactive       campaign                0.00            0
30        inactive       campaign                0.00            0
29        inactive       campaign                0.00            0
28        inactive       campaign                0.00            0
27        inactive       campaign              403.43         1142
26        inactive       campaign              681.39         2202
25        inactive       campaign             1941.11        14964
24        inactive       campaign              705.63         2007
23        inactive       campaign             2001.02        17955
22        inactive       campaign              300.96          935
20        inactive       campaign             2009.33        20969
21          active       campaign              662.74        10678
19        inactive       campaign             1997.54        21374
18          active       campaign              973.36        16814
17        inactive       campaign                0.00            0
16        inactive       campaign             1982.31        22149
15          active       campaign              954.40        15002
14        inactive       campaign                0.00            0
13        inactive       campaign             1983.00        24625
12          active       campaign              991.47        15609
10        inactive       campaign             1941.17        25353
11          active       campaign              964.12        18951
9         inactive       campaign             1573.42        20822
8           active       campaign              815.22        16770
7           active       campaign                0.00            0
6         inactive       campaign                0.00            0
5           active       campaign                0.00            0
4           active       campaign                0.00            0
3         inactive       campaign                0.00            0
2           active       campaign                0.00            0
1         inactive       campaign              497.70         5774
0           active       campaign             1033.89        21966

    CPM (cost per 1,000 impressions)  Reach  Frequency  \
45                         147.32580   2983   1.101911
44                         111.02610  15080   1.134814
43                               NaN      0   0.000000
42                         106.72180  16578   1.071661
41                         136.91600   2621   1.071347
40                               NaN      0   0.000000
39                               NaN      0   0.000000
38                         117.76740  12323   1.047553
37                         397.22840    869   1.133487
36                               NaN      0   0.000000
35                               NaN      0   0.000000
34                               NaN      0   0.000000
32                               NaN      0   0.000000
33                               NaN      0   0.000000
31                               NaN      0   0.000000
30                               NaN      0   0.000000
29                               NaN      0   0.000000
28                               NaN      0   0.000000
27                         353.26620   1019   1.120707
26                         309.44140   1843   1.194791
25                         129.71870  13111   1.141332
24                         351.58450   1737   1.155440
23                         111.44640  15921   1.127756
22                         321.88240    868   1.077189
20                          95.82384  18648   1.124464
21                          62.06593   8773   1.217144
19                          93.45654  20110   1.062854
18                          57.88985  14389   1.168532
17                               NaN      0   0.000000
16                          89.49885  20667   1.071709
15                          63.61818  12858   1.166744
14                               NaN      0   0.000000
13                          80.52792  23030   1.069257
12                          63.51912  13346   1.169564
10                          76.56569  23188   1.093367
11                          50.87436  16761   1.130660
9                           75.56527  19635   1.060453
8                           48.61181  15373   1.090874
7                                NaN      0   0.000000
6                                NaN      0   0.000000
5                                NaN      0   0.000000
4                                NaN      0   0.000000
3                                NaN      0   0.000000
2                                NaN      0   0.000000
1                           86.19674   5590   1.032916
0                           47.06774  20810   1.055550

    CTR (link click-through rate)  ...  CTR (all)  Link clicks  \
45                       0.973532  ...   2.220870         32.0
44                       1.472565  ...   2.594519        252.0
43                            NaN  ...        NaN          NaN
42                       0.990656  ...   2.054486        176.0
41                       0.641026  ...   1.851852         18.0
40                            NaN  ...        NaN          NaN
39                            NaN  ...        NaN          NaN
38                       0.999303  ...   2.277481        129.0
37                       3.756345  ...   7.208122         37.0
36                            NaN  ...        NaN          NaN
35                            NaN  ...        NaN          NaN
34                            NaN  ...        NaN          NaN
32                            NaN  ...        NaN          NaN
33                            NaN  ...        NaN          NaN
31                            NaN  ...        NaN          NaN
30                            NaN  ...        NaN          NaN
29                            NaN  ...        NaN          NaN
28                            NaN  ...        NaN          NaN
27                       2.539405  ...   5.166375         29.0
26                       2.406903  ...   6.130790         53.0
25                       0.668271  ...   1.376637        100.0
24                       2.142501  ...   5.281515         43.0
23                       0.540239  ...   1.203008         97.0
22                       1.497326  ...   4.705882         14.0
20                       0.643808  ...   1.192236        135.0
21                       0.739839  ...   1.788724         79.0
19                       0.430429  ...   0.982502         92.0
18                       0.802902  ...   1.903176        135.0
17                            NaN  ...        NaN          NaN
16                       0.501151  ...   1.047451        111.0
15                       0.933209  ...   2.326356        140.0
14                            NaN  ...        NaN          NaN
13                       0.410152  ...   0.787817        101.0
12                       0.858479  ...   2.312768        134.0
10                       0.402319  ...   0.938745        102.0
11                       0.733471  ...   2.100153        139.0
9                        0.470656  ...   1.022956         98.0
8                        1.079308  ...   2.474657        181.0
7                             NaN  ...        NaN          NaN
6                             NaN  ...        NaN          NaN
5                             NaN  ...        NaN          NaN
4                             NaN  ...        NaN          NaN
3                             NaN  ...        NaN          NaN
2                             NaN  ...        NaN          NaN
1                        0.381018  ...   0.865951         22.0
0                        0.883183  ...   1.884731        194.0

    Landing page views              Result Type  Results  \
45                18.0                      NaN      NaN
44               209.0        Website purchases     12.0
43                 NaN             paid47Second      1.0
42               135.0        Website purchases      5.0
41                 8.0  freewebinarThankyoupage      3.0
40                 NaN  freewebinarThankyoupage      3.0
39                 NaN                      NaN      NaN
38                99.0        Website purchases      8.0
37                30.0                      NaN      NaN
36                 NaN  freewebinarThankyoupage      1.0
35                 NaN                      NaN      NaN
34                 NaN        Website purchases      1.0
32                 NaN                      NaN      NaN
33                 NaN                      NaN      NaN
31                 NaN  freewebinarThankyoupage      1.0
30                 NaN                      NaN      NaN
29                 NaN                      NaN      NaN
28                 NaN        Website purchases      1.0
27                22.0                      NaN      NaN
26                40.0                      NaN      NaN
25                80.0             paid47Second     21.0
24                36.0                      NaN      NaN
23                63.0             paid47Second     10.0
22                12.0                      NaN      NaN
20                87.0             paid47Second     18.0
21                50.0  freewebinarThankyoupage      2.0
19                75.0             paid47Second     11.0
18               102.0  freewebinarThankyoupage      4.0
17                 NaN                      NaN      NaN
16                90.0             paid47Second     20.0
15                74.0  freewebinarThankyoupage      3.0
14                 NaN                      NaN      NaN
13                71.0             paid47Second     11.0
12                76.0                      NaN      NaN
10                72.0             paid47Second     15.0
11                98.0  freewebinarThankyoupage      4.0
9                 65.0             paid47Second      5.0
8                 97.0  freewebinarThankyoupage      6.0
7                  NaN  freewebinarThankyoupage      4.0
6                  NaN                      NaN      NaN
5                  NaN  freewebinarThankyoupage      3.0
4                  NaN  freewebinarThankyoupage      1.0
3                  NaN                      NaN      NaN
2                  NaN  freewebinarThankyoupage      1.0
1                 14.0                      NaN      1.0
0                 91.0  freewebinarThankyoupage      9.0

   Purchase ROAS (return on ad spend)        Attribution setting  \
45                                NaN  7-day click or 1-day view
44                           1.888431  7-day click or 1-day view
43                                NaN  7-day click or 1-day view
42                           0.788494  7-day click or 1-day view
41                                NaN  7-day click or 1-day view
40                                NaN  7-day click or 1-day view
39                                NaN  7-day click or 1-day view
38                           1.573415  7-day click or 1-day view
37                                NaN  7-day click or 1-day view
36                                NaN  7-day click or 1-day view
35                                NaN  7-day click or 1-day view
34                                NaN  7-day click or 1-day view
32                                NaN  7-day click or 1-day view
33                                NaN  7-day click or 1-day view
31                                NaN  7-day click or 1-day view
30                                NaN  7-day click or 1-day view
29                                NaN  7-day click or 1-day view
28                                NaN  7-day click or 1-day view
27                                NaN  7-day click or 1-day view
26                                NaN  7-day click or 1-day view
25                           0.069548  7-day click or 1-day view
24                                NaN  7-day click or 1-day view
23                           0.040479  7-day click or 1-day view
22                                NaN  7-day click or 1-day view
20                           0.058228  7-day click or 1-day view
21                                NaN  7-day click or 1-day view
19                           0.045055  7-day click or 1-day view
18                                NaN  7-day click or 1-day view
17                                NaN  7-day click or 1-day view
16                           0.063562  7-day click or 1-day view
15                                NaN  7-day click or 1-day view
14                                NaN  7-day click or 1-day view
13                           0.027231  7-day click or 1-day view
12                                NaN  7-day click or 1-day view
10                           0.027818  7-day click or 1-day view
11                                NaN  7-day click or 1-day view
9                            0.028600  7-day click or 1-day view
8                                 NaN  7-day click or 1-day view
7                                 NaN  7-day click or 1-day view
6                                 NaN  7-day click or 1-day view
5                                 NaN  7-day click or 1-day view
4                                 NaN  7-day click or 1-day view
3                                 NaN  7-day click or 1-day view
2                                 NaN  7-day click or 1-day view
1                                 NaN  7-day click or 1-day view
0                                 NaN  7-day click or 1-day view

    Cost per result Reporting starts  Reporting ends
45              NaN         3/1/2024        3/1/2024
44         158.3325         3/1/2024        3/1/2024
43           0.0000         3/1/2024        3/1/2024
42         379.2040         3/2/2024        3/2/2024
41         128.1533         3/2/2024        3/2/2024
40           0.0000         3/3/2024        3/3/2024
39              NaN         3/3/2024        3/3/2024
38         190.0325         3/3/2024        3/3/2024
37              NaN         3/3/2024        3/3/2024
36           0.0000         3/4/2024        3/4/2024
35              NaN         3/4/2024        3/4/2024
34           0.0000         3/4/2024        3/4/2024
32              NaN         3/5/2024        3/5/2024
33              NaN         3/5/2024        3/5/2024
31           0.0000         3/6/2024        3/6/2024
30              NaN         3/6/2024        3/6/2024
29              NaN         3/7/2024        3/7/2024
28           0.0000         3/8/2024        3/8/2024
27              NaN        3/16/2024       3/16/2024
26              NaN        3/17/2024       3/17/2024
25         323.5183        3/17/2024       3/17/2024
24              NaN        3/18/2024       3/18/2024
23         500.2550        3/18/2024       3/18/2024
22              NaN        3/19/2024       3/19/2024
20         669.7767        3/19/2024       3/19/2024
21         331.3700        3/19/2024       3/19/2024
19         399.5080        3/20/2024       3/20/2024
18         243.3400        3/20/2024       3/20/2024
17              NaN        3/21/2024       3/21/2024
16         283.1871        3/21/2024       3/21/2024
15         318.1333        3/21/2024       3/21/2024
14              NaN        3/22/2024       3/22/2024
13         661.0000        3/22/2024       3/22/2024
12              NaN        3/22/2024       3/22/2024
10         970.5850        3/23/2024       3/23/2024
11         241.0300        3/23/2024       3/23/2024
9         1573.4200        3/24/2024       3/24/2024
8          135.8700        3/24/2024       3/24/2024
7            0.0000        3/25/2024       3/25/2024
6               NaN        3/26/2024       3/26/2024
5            0.0000        3/26/2024       3/26/2024
4            0.0000        3/27/2024       3/27/2024
3               NaN        3/28/2024       3/28/2024
2            0.0000        3/29/2024       3/29/2024

In [4]:
df=pd.DataFrame(df)
df.fillna(0, inplace=True)
df=df.reset_index(drop=True)
df.head()

,Campaign name,Day,Delivery status,Delivery level,Amount spent (INR),Impressions,"CPM (cost per 1,000 impressions)",Reach,Frequency,CTR (link click-through rate),...,CTR (all),Link clicks,Landing page views,Result Type,Results,Purchase ROAS (return on ad spend),Attribution setting,Cost per result,Reporting starts,Reporting ends
0,Foreign|Sales|Tamil,1Mar (Fri),inactive,campaign,484.26,3287,147.3258,2983,1.101911,0.973532,...,2.220870,32.0,18.0,0,0.0,0.000000,7-day click or 1-day view,0.0000,3/1/2024,3/1/2024
1,3dayslive – Copy 2 - Advantage+ shopping campaign,1Mar (Fri),inactive,campaign,1899.99,17113,111.0261,15080,1.134814,1.472565,...,2.594519,252.0,209.0,Website purchases,12.0,1.888431,7-day click or 1-day view,158.3325,3/1/2024,3/1/2024
2,3dayslive – Copy,1Mar (Fri),inactive,campaign,0.00,0,0.0000,0,0.000000,0.000000,...,0.000000,0.0,0.0,paid47Second,1.0,0.000000,7-day click or 1-day view,0.0000,3/1/2024,3/1/2024
3,3dayslive – Copy 2 - Advantage+ shopping campaign,2Mar (Sat),inactive,campaign,1896.02,17766,106.7218,16578,1.071661,0.990656,...,2.054486,176.0,135.0,Website purchases,5.0,0.788494,7-day click or 1-day view,379.2040,3/2/2024,3/2/2024
4,Foreign|Sales|Tamil,2Mar (Sat),inactive,campaign,384.46,2808,136.9160,2621,1.071347,0.641026,...,1.851852,18.0,8.0,freewebinarThankyoupage,3.0,0.000000,7-day click or 1-day view,128.1533,3/2/2024,3/2/2024

In [5]:
data = df[['Day', 'Campaign name', 'Amount spent (INR)', 'Results', 'CTR (link click-through rate)', 'Link clicks', 'Landing page views']]

# Rename columns
data.rename(columns={'Day':'Date','Amount spent (INR)': 'AD Spent', 'Results': 'No of leads', 'CTR (link click-through rate)': 'CTR', 'Landing page views': 'LP Views'}, inplace=True)

data.fillna(0, inplace=True)

# Calculate Cost per Lead
data['Cost per Lead'] = data['AD Spent'] / data['No of leads']

# Calculate Member passed
data['Member passed'] = data['LP Views'] / data['Link clicks']*100
  

# Calculate LP Conversion
data['LP Conversion%'] = data['No of leads'] / data['LP Views']*100


data.head()

C:\Users\udhaya\Anaconda3\envs\aim1\lib\site-packages\pandas\core\frame.py:4238: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(**kwargs)
C:\Users\udhaya\Anaconda3\envs\aim1\lib\site-packages\pandas\core\frame.py:4259: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  **kwargs
C:\Users\udhaya\Anaconda3\envs\aim1\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == "__main__":
C:\Users\udhaya\Anaconda3\envs\aim1\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == "":
C:\Users\udhaya\Anaconda3\envs\aim1\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Date,Campaign name,AD Spent,No of leads,CTR,Link clicks,LP Views,Cost per Lead,Member passed,LP Conversion%
0,1Mar (Fri),Foreign|Sales|Tamil,484.26,0.0,0.973532,32.0,18.0,inf,56.250000,0.000000
1,1Mar (Fri),3dayslive – Copy 2 - Advantage+ shopping campaign,1899.99,12.0,1.472565,252.0,209.0,158.332500,82.936508,5.741627
2,1Mar (Fri),3dayslive – Copy,0.00,1.0,0.000000,0.0,0.0,0.000000,NaN,inf
3,2Mar (Sat),3dayslive – Copy 2 - Advantage+ shopping campaign,1896.02,5.0,0.990656,176.0,135.0,379.204000,76.704545,3.703704
4,2Mar (Sat),Foreign|Sales|Tamil,384.46,3.0,0.641026,18.0,8.0,128.153333,44.444444,37.500000

In [6]:
data = data[['Date', 'Campaign name', 'AD Spent', 'No of leads','Cost per Lead', 'CTR',
       'Link clicks', 'LP Views', 'Member passed',
       'LP Conversion%']]
data.head()

,Date,Campaign name,AD Spent,No of leads,Cost per Lead,CTR,Link clicks,LP Views,Member passed,LP Conversion%
0,1Mar (Fri),Foreign|Sales|Tamil,484.26,0.0,inf,0.973532,32.0,18.0,56.250000,0.000000
1,1Mar (Fri),3dayslive – Copy 2 - Advantage+ shopping campaign,1899.99,12.0,158.332500,1.472565,252.0,209.0,82.936508,5.741627
2,1Mar (Fri),3dayslive – Copy,0.00,1.0,0.000000,0.000000,0.0,0.0,NaN,inf
3,2Mar (Sat),3dayslive – Copy 2 - Advantage+ shopping campaign,1896.02,5.0,379.204000,0.990656,176.0,135.0,76.704545,3.703704
4,2Mar (Sat),Foreign|Sales|Tamil,384.46,3.0,128.153333,0.641026,18.0,8.0,44.444444,37.500000

# over all results (all compaign name)

In [7]:
# Define the new campaign names
new_campaign_name_1 = 'Foreign|Sales|Tamil - Advantage+ shopping camp'
new_campaign_name_2 = '3dayslive – Copy 2 - Advantage+ shopping campaign'

# Changing the campaign names in the DataFrame
data.loc[data['Campaign name'].str.contains('Foreign|Sales|Tamil - Advantage+ shopping camp'), 'Campaign name'] = new_campaign_name_1
data.loc[data['Campaign name'].str.contains('3dayslive – Copy 2 - Advantage+ shopping campaign') | data['Campaign name'].str.contains('3dayslive – Copy'), 'Campaign name'] = new_campaign_name_2

data.head()

,Date,Campaign name,AD Spent,No of leads,Cost per Lead,CTR,Link clicks,LP Views,Member passed,LP Conversion%
0,1Mar (Fri),Foreign|Sales|Tamil - Advantage+ shopping camp,484.26,0.0,inf,0.973532,32.0,18.0,56.250000,0.000000
1,1Mar (Fri),3dayslive – Copy 2 - Advantage+ shopping campaign,1899.99,12.0,158.332500,1.472565,252.0,209.0,82.936508,5.741627
2,1Mar (Fri),3dayslive – Copy 2 - Advantage+ shopping campaign,0.00,1.0,0.000000,0.000000,0.0,0.0,NaN,inf
3,2Mar (Sat),3dayslive – Copy 2 - Advantage+ shopping campaign,1896.02,5.0,379.204000,0.990656,176.0,135.0,76.704545,3.703704
4,2Mar (Sat),Foreign|Sales|Tamil - Advantage+ shopping camp,384.46,3.0,128.153333,0.641026,18.0,8.0,44.444444,37.500000

# 3dayslive – Copy 2 - Advantage+ shopping campaign']

In [8]:
datanew=data[data['Campaign name']=='3dayslive – Copy 2 - Advantage+ shopping campaign']
datanew

,Date,Campaign name,AD Spent,No of leads,Cost per Lead,CTR,Link clicks,LP Views,Member passed,LP Conversion%
1,1Mar (Fri),3dayslive – Copy 2 - Advantage+ shopping campaign,1899.99,12.0,158.3325,1.472565,252.0,209.0,82.936508,5.741627
2,1Mar (Fri),3dayslive – Copy 2 - Advantage+ shopping campaign,0.00,1.0,0.0000,0.000000,0.0,0.0,NaN,inf
3,2Mar (Sat),3dayslive – Copy 2 - Advantage+ shopping campaign,1896.02,5.0,379.2040,0.990656,176.0,135.0,76.704545,3.703704
6,3Mar (Sun),3dayslive – Copy 2 - Advantage+ shopping campaign,0.00,0.0,NaN,0.000000,0.0,0.0,NaN,NaN
7,3Mar (Sun),3dayslive – Copy 2 - Advantage+ shopping campaign,1520.26,8.0,190.0325,0.999303,129.0,99.0,76.744186,8.080808
10,4Mar (Mon),3dayslive – Copy 2 - Advantage+ shopping campaign,0.00,0.0,NaN,0.000000,0.0,0.0,NaN,NaN
11,4Mar (Mon),3dayslive – Copy 2 - Advantage+ shopping campaign,0.00,1.0,0.0000,0.000000,0.0,0.0,NaN,inf
12,5Mar (Tue),3dayslive – Copy 2 - Advantage+ shopping campaign,0.00,0.0,NaN,0.000000,0.0,0.0,NaN,NaN
13,5Mar (Tue),3dayslive – Copy 2 - Advantage+ shopping campaign,0.00,0.0,NaN,0.000000,0.0,0.0,NaN,NaN
15,6Mar (Wed),3dayslive – Copy 2 - Advantage+ shopping campaign,0.00,0.0,NaN,0.000000,0.0,0.0,NaN,NaN
16,7Mar (Thu),3dayslive – Copy 2 - Advantage+ shopping campaign,0.00,0.0,NaN,0.000000,0.0,0.0,NaN,NaN
17,8Mar (Fri),3dayslive – Copy 2 - Advantage+ shopping campaign,0.00,1.0,0.0000,0.000000,0.0,0.0,NaN,inf

# Foreign|Sales|Tamil - Advantage+ shopping camp

In [9]:
datanew=data[data['Campaign name']=='Foreign|Sales|Tamil - Advantage+ shopping camp']
datanew

,Date,Campaign name,AD Spent,No of leads,Cost per Lead,CTR,Link clicks,LP Views,Member passed,LP Conversion%
0,1Mar (Fri),Foreign|Sales|Tamil - Advantage+ shopping camp,484.26,0.0,inf,0.973532,32.0,18.0,56.250000,0.000000
4,2Mar (Sat),Foreign|Sales|Tamil - Advantage+ shopping camp,384.46,3.0,128.153333,0.641026,18.0,8.0,44.444444,37.500000
5,3Mar (Sun),Foreign|Sales|Tamil - Advantage+ shopping camp,0.00,3.0,0.000000,0.000000,0.0,0.0,NaN,inf
8,3Mar (Sun),Foreign|Sales|Tamil - Advantage+ shopping camp,391.27,0.0,inf,3.756345,37.0,30.0,81.081081,0.000000
9,4Mar (Mon),Foreign|Sales|Tamil - Advantage+ shopping camp,0.00,1.0,0.000000,0.000000,0.0,0.0,NaN,inf
14,6Mar (Wed),Foreign|Sales|Tamil - Advantage+ shopping camp,0.00,1.0,0.000000,0.000000,0.0,0.0,NaN,inf
18,16Mar (Sat),Foreign|Sales|Tamil - Advantage+ shopping camp,403.43,0.0,inf,2.539405,29.0,22.0,75.862069,0.000000
19,17Mar (Sun),Foreign|Sales|Tamil - Advantage+ shopping camp,681.39,0.0,inf,2.406903,53.0,40.0,75.471698,0.000000
21,18Mar (Mon),Foreign|Sales|Tamil - Advantage+ shopping camp,705.63,0.0,inf,2.142501,43.0,36.0,83.720930,0.000000
23,19Mar (Tue),Foreign|Sales|Tamil - Advantage+ shopping camp,300.96,0.0,inf,1.497326,14.0,12.0,85.714286,0.000000
25,19Mar (Tue),Foreign|Sales|Tamil - Advantage+ shopping camp,662.74,2.0,331.370000,0.739839,79.0,50.0,63.291139,4.000000
27,20Mar (Wed),Foreign|Sales|Tamil - Advantage+ shopping camp,973.36,4.0,243.340000,0.802902,135.0,102.0,75.555556,3.921569
28,21Mar (Thu),Foreign|Sales|Tamil - Advantage+ shopping camp,0.00,0.0,NaN,0.000000,0.0,0.0,NaN,NaN
30,21Mar (Thu),Foreign|Sales|Tamil - Advantage+ shopping camp,954.40,3.0,318.133333,0.933209,140.0,74.0,52.857143,4.054054
31,22Mar (Fri),Foreign|Sales|Tamil - Advantage+ shopping camp,0.00,0.0,NaN,0.000000,0.0,0.0,NaN,NaN
33,22Mar (Fri),Foreign|Sales|Tamil - Advantage+ shopping camp,991.47,0.0,inf,0.858479,134.0,76.0,56.716418,0.000000
35,23Mar (Sat),Foreign|Sales|Tamil - Advantage+ shopping camp,964.12,4.0,241.030000,0.733471,139.0,98.0,70.503597,4.081633
37,24Mar (Sun),Foreign|Sales|Tamil - Advantage+ shopping camp,815.22,6.0,135.870000,1.079308,181.0,97.0,53.591160,6.185567
38,25Mar (Mon),Foreign|Sales|Tamil - Advantage+ shopping camp,0.00,4.0,0.000000,0.000000,0.0,0.0,NaN,inf
40,26Mar (Tue),Foreign|Sales|Tamil - Advantage+ shopping camp,0.00,3.0,0.000000,0.000000,0.0,0.0,NaN,inf
41,27Mar (Wed),Foreign|Sales|Tamil - Advantage+ shopping camp,0.00,1.0,0.000000,0.000000,0.0,0.0,NaN,inf
43,29Mar (Fri),Foreign|Sales|Tamil - Advantage+ shopping camp,0.00,1.0,0.000000,0.000000,0.0,0.0,NaN,inf
45,31Mar (Sun),Foreign|Sales|Tamil - Advantage+ shopping camp,1033.89,9.0,114.876667,0.883183,194.0,91.0,46.907216,9.890110

# Campaign name-Feedbackrs9

In [10]:
datanew=data[data['Campaign name']=='Feedbackrs9']
datanew

,Date,Campaign name,AD Spent,No of leads,Cost per Lead,CTR,Link clicks,LP Views,Member passed,LP Conversion%
20,17Mar (Sun),Feedbackrs9,1941.11,21.0,92.433810,0.668271,100.0,80.0,80.000000,26.250000
22,18Mar (Mon),Feedbackrs9,2001.02,10.0,200.102000,0.540239,97.0,63.0,64.948454,15.873016
24,19Mar (Tue),Feedbackrs9,2009.33,18.0,111.629444,0.643808,135.0,87.0,64.444444,20.689655
26,20Mar (Wed),Feedbackrs9,1997.54,11.0,181.594545,0.430429,92.0,75.0,81.521739,14.666667
29,21Mar (Thu),Feedbackrs9,1982.31,20.0,99.115500,0.501151,111.0,90.0,81.081081,22.222222
32,22Mar (Fri),Feedbackrs9,1983.00,11.0,180.272727,0.410152,101.0,71.0,70.297030,15.492958
34,23Mar (Sat),Feedbackrs9,1941.17,15.0,129.411333,0.402319,102.0,72.0,70.588235,20.833333
36,24Mar (Sun),Feedbackrs9,1573.42,5.0,314.684000,0.470656,98.0,65.0,66.326531,7.692308
39,26Mar (Tue),Feedbackrs9,0.00,0.0,NaN,0.000000,0.0,0.0,NaN,NaN
42,28Mar (Thu),Feedbackrs9,0.00,0.0,NaN,0.000000,0.0,0.0,NaN,NaN
44,31Mar (Sun),Feedbackrs9,497.70,1.0,497.700000,0.381018,22.0,14.0,63.636364,7.142857